Updated solidity version to 0.8.20;
Updated solidity version to 0.8.20; 

To solve the compile time error

```
ParserError: Source file requires different compiler version (current compiler is 0.8.15+commit.e14f2714.Emscripten.clang).
```