Updated solidity version to 0.8.20; & Added Address.sol library
Added Address.sol library to solve this error 
```
DeclarationError: Identifier is not a library name.
 --> contracts/testRearSkill.sol:7:11:
  |
7 |     using Address for address;
  |           ^^^^^^^

```

and solidity version to 0.8.20 to solve this error 
```
ParserError: Source file requires different compiler version (current compiler is 0.8.15+commit.e14f2714.Emscripten.clang) 

```